[package]
name = "amect"
description = "Central AME tooklit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
eframe = "0.21"
image = "0.24.5"
inquire = "0.6"
native-dialog = { version = "0.6.3", features = [
    "windows_dpi_awareness",
    "windows_visual_styles",
] }
widestring = "1.0.2"
dirs = "5.0"
[target.'cfg(windows)'.dependencies]
winreg = "0.11"
[dependencies.windows]
version = "0.46"
features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_System",
    "Win32_System_WindowsProgramming",
    "Win32_NetworkManagement_NetManagement",
]

[profile.release]
strip = true
opt-level = "s"
lto = true
panic = "abort"
